name: Go

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: true
      CCACHE_MAXSIZE: 1G
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ runner.os }}-${{ github.sha }}
        restore-keys: ${{ runner.os }}

    - name: Install go-bindata
      run: |
        # go get -u -v github.com/kevinburke/go-bindata/...
        go install github.com/kevinburke/go-bindata/go-bindata@v3.24.0

    - name: Build
      run: |
        cd cmd/magneticod ; go mod tidy; cd -
        # make magneticod
        #go install --tags fts5 "-ldflags=-s -w -X main.compiledOn=`date -u +%Y-%m-%dT%H:%M:%SZ`" ./cmd/magneticod
        go build --tags fts5 "-ldflags=-s -w -X main.compiledOn=`date -u +%Y-%m-%dT%H:%M:%SZ`" ./cmd/magneticod

        #cd cmd/magneticow ; go mod tidy; cd - ; make magneticow
        #GOOS=windows GOARCH=amd64 go build
        ls -laR

    #- name: Test
    #  run: |
    #    make test

    #- name: Lint
    #  run: |
    #    make staticcheck

    #- name: Check Formatting
    #  run: |
    #    make check-formatting

    - name: Package (*nix)
      if: runner.os != 'Windows'
      run: >
        tar -cv README.md magneticod magneticow | gzip --best > '${{ runner.os }}.tar.gz'
    - name: Package (Windows)
      if: runner.os == 'Windows'
      run: >
        7z a ${{ runner.os }}.zip README.md magneticod.exe magneticow.exe
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }} # ${{ matrix.target }}
        path: |
          ${{ runner.os }}.tar.gz
          ${{ runner.os }}.zip

    #- name: Create release
    #  if: startsWith(github.ref, 'refs/tags/v')
    #  uses: softprops/action-gh-release@v1
    #  with:
    #    draft: true
    #    files: |
    #      *.zip
    #      *.tar.gz
