name: Go

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install go-bindata
      run: |
        # go get -u -v github.com/kevinburke/go-bindata/...
        go install github.com/kevinburke/go-bindata/go-bindata@v3.24.0

    - name: Build
      run: |
        cd cmd/magneticod ; go mod tidy; cd -; make magneticod
        cd cmd/magneticow ; go mod tidy; cd - ; make magneticow

    #- name: Test
    #  run: |
    #    make test

    #- name: Lint
    #  run: |
    #    make staticcheck

    #- name: Check Formatting
    #  run: |
    #    make check-formatting

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact # ${{ matrix.target }}
        path: |
          *.zip
          *.tar.gz
    #- name: Create release
    #  if: startsWith(github.ref, 'refs/tags/v')
    #  uses: softprops/action-gh-release@v1
    #  with:
    #    draft: true
    #    files: |
    #      *.zip
    #      *.tar.gz
