name: Go magneticod for Windows

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOCACHE: ${{ github.workspace }}/.gocache

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Cache Files
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.gocache
        key: ${{ runner.os }}-gocache-file

    - name: Install go-bindata
      run: |
        go install github.com/kevinburke/go-bindata/go-bindata@v3.24.0

    - name: Mod tidy
      run: |
        go mod tidy
        # cd cmd/magneticow ; go mod tidy; cd - 

    - name: Build magneticod.exe
      run: |
        GOOS=windows GOARCH=amd64 go build --tags fts5 "-ldflags=-s -w -X main.compiledOn=`date -u +%Y-%m-%dT%H:%M:%SZ`" ./cmd/magneticod

    - name: Build magneticow bindata
      run: |
        go-bindata -pkg "main" -o="cmd/magneticow/bindata.go" -prefix="cmd/magneticow/data/" cmd/magneticow/data/...
        sed -i '1s;^;//lint:file-ignore * Ignore file altogether\n;' cmd/magneticow/bindata.go

    - name: Build magneticow
      run: |
        # make magneticow
        go build --tags fts5 "-ldflags=-s -w -X main.compiledOn=`date -u +%Y-%m-%dT%H:%M:%SZ`" ./cmd/magneticow

    - name: List Package dir
      run: |
        ls -la

    - name: Upload artifact Win
      uses: actions/upload-artifact@v2
      with:
        name: magnetico.win64
        path: |
          README.md
          magneticod.exe
          magneticow.exe    
